# Generated by Django 2.0.12 on 2019-12-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_goods', '0001_initial'),
        ('df_user', '0003_userinfo_user_algorihtm_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_data_url', models.CharField(max_length=200, verbose_name='task_data_url')),
                ('task_start_time', models.DateTimeField(verbose_name='task start time')),
                ('task_end_time', models.DateTimeField(verbose_name='task end time')),
                ('task_status', models.IntegerField(default=0, verbose_name='task_status')),
                ('task_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo')),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='task user')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'task',
            },
        ),
    ]
