# Generated by Django 2.0.12 on 2019-12-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_task', '0002_auto_20191226_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.CharField(default='0', max_length=100, verbose_name='out'),
        ),
    ]
