# Generated by Django 2.0.12 on 2019-12-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_task', '0003_task_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='task end time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='task start time'),
        ),
    ]
