# Generated by Django 3.0.2 on 2020-01-16 23:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0013_auto_20200116_1159'),
        ('df_task', '0004_auto_20191226_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务信息表', 'verbose_name_plural': '任务信息表'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_algorithm',
            new_name='algorithm',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='task',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_data_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_user',
        ),
        migrations.AddField(
            model_name='task',
            name='cfg_file',
            field=models.FileField(blank=True, null=True, upload_to='task/%Y-%m', verbose_name='配置模板地址'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='task_status'),
        ),
        migrations.AddField(
            model_name='task',
            name='update_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='上次修改时间'),
        ),
    ]
