# Generated by Django 3.0.2 on 2020-01-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_task', '0005_auto_20200116_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cfg_file',
            field=models.CharField(default='', max_length=10000, verbose_name='配置模板'),
        ),
    ]
