# Generated by Django 3.0.2 on 2020-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_task', '0007_auto_20200118_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='update_time',
            field=models.TimeField(default=1579332077.8999693, verbose_name='上次修改时间'),
        ),
    ]
