# Generated by Django 2.0.12 on 2019-12-08 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_payment_account',
            field=models.CharField(default=uuid.uuid1, max_length=20, unique=True, verbose_name='user payment account'),
        ),
    ]
