# Generated by Django 2.0.12 on 2019-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
        ('df_user', '0002_userinfo_user_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_algorihtm_bought',
            field=models.ManyToManyField(to='df_goods.GoodsInfo'),
        ),
    ]
