# Generated by Django 2.0.12 on 2019-12-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_userinfo_user_algorihtm_bought'),
        ('df_user', '0006_auto_20190427_2158'),
    ]

    operations = [
    ]
