# Generated by Django 2.0.12 on 2019-12-08 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20191208_1602'),
        ('df_user', '0007_merge_20191208_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '卖家信息',
                'verbose_name_plural': '卖家信息',
            },
        ),
    ]
