# Generated by Django 2.0.12 on 2019-12-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0008_sellerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinfo',
            name='good',
        ),
        migrations.RemoveField(
            model_name='sellerinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_algorihtm_bought',
        ),
        migrations.DeleteModel(
            name='SellerInfo',
        ),
    ]
