# Generated by Django 2.0.12 on 2019-12-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0008_auto_20191208_2237'),
        ('df_user', '0009_auto_20191208_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuyAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户购买的算法',
                'verbose_name_plural': '用户购买的算法',
            },
        ),
    ]
