# Generated by Django 2.0.12 on 2019-12-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0010_userbuyalgorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='用户文件名')),
                ('file_uuid', models.CharField(max_length=100, verbose_name='文件uuid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户文件',
                'verbose_name_plural': '用户文件',
            },
        ),
    ]
