# Generated by Django 3.0.2 on 2020-01-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0011_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='创建任务名')),
                ('config_context', models.TextField(verbose_name='用户创建的任务配置信息')),
                ('task_status', models.CharField(max_length=50, verbose_name='任务状态')),
                ('last_update', models.TimeField(verbose_name='算法状态更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uaddress',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uphone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_payment_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ushou',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uyoubian',
        ),
        migrations.DeleteModel(
            name='GoodsBrowser',
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
        migrations.AddField(
            model_name='usercreatetask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户ID'),
        ),
    ]
