# Generated by Django 3.0.2 on 2020-01-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0012_auto_20200115_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercreatetask',
            options={'verbose_name': '用户创建的算法任务', 'verbose_name_plural': '用户创建的算法任务'},
        ),
    ]
