# Generated by Django 3.0.2 on 2020-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0014_auto_20200117_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机号码'),
        ),
    ]
