# Generated by Django 3.0.2 on 2020-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0015_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号码'),
        ),
    ]
