# Generated by Django 2.0.12 on 2019-12-08 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('gtitle', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('gpic', models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='商品图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('gunit', models.CharField(default='500g', max_length=20, verbose_name='单位重量')),
                ('gclick', models.IntegerField(default=0, verbose_name='点击量')),
                ('gjianjie', models.CharField(max_length=200, verbose_name='简介')),
                ('gkucun', models.IntegerField(default=0, verbose_name='库存')),
                ('gcontent', tinymce.models.HTMLField(max_length=1000, verbose_name='详情')),
                ('algorithm_sale_count', models.IntegerField(default=0, verbose_name='sale_count')),
                ('algorithm_code_url', models.CharField(default='', max_length=200, verbose_name='algorithm_code_url')),
                ('algorithm_document_url', models.CharField(default='', max_length=200, verbose_name='algorithm_document_url')),
                ('algorithm_status', models.IntegerField(default=0)),
                ('algorithm_market_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ttitle', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo', verbose_name='分类'),
        ),
    ]
