# Generated by Django 2.0.12 on 2019-12-08 16:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20190427_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='algorithm_code_url',
            field=models.CharField(default='', max_length=200, verbose_name='代码链接'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='algorithm_document_url',
            field=models.CharField(default='', max_length=200, verbose_name='文档链接'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='algorithm_sale_count',
            field=models.IntegerField(default=0, verbose_name='销售量'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gcontent',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='1h', max_length=20, verbose_name='单位重量'),
        ),
    ]
