# Generated by Django 2.0.12 on 2019-12-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20191208_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='algorithm_sale_count',
            new_name='gsale',
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='algorithm_status',
            new_name='gstatus',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='algorithm_code_url',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='algorithm_document_url',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gcode',
            field=models.FileField(blank=True, null=True, upload_to='code/%Y-%m', verbose_name='算法代码'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gdoc',
            field=models.FileField(default='', upload_to='doc/%Y-%m', verbose_name='文档链接'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y-%m', verbose_name='商品图片'),
        ),
    ]
