# Generated by Django 2.0.12 on 2019-12-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0005_auto_20191208_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gdoc',
            field=models.FileField(blank=True, null=True, upload_to='doc/%Y-%m', verbose_name='文档链接'),
        ),
    ]
