# Generated by Django 2.0.12 on 2019-12-08 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0009_auto_20191208_2237'),
        ('df_goods', '0007_auto_20191208_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gmdf_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='guser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='用户ID'),
            preserve_default=False,
        ),
    ]
