# Generated by Django 2.0.12 on 2019-12-26 13:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0009_auto_20191226_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gcontent',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='详情'),
        ),
    ]
