# Generated by Django 3.0.2 on 2020-01-16 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0011_remove_goodsinfo_guser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '商品信息表', 'verbose_name_plural': '商品信息表'},
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gtitle',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gtype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='typeinfo',
            old_name='ttitle',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='algorithm_market_time',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gclick',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gcode',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gcontent',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gdoc',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gjianjie',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gmdf_time',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gpic',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gprice',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gsale',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gstatus',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='cfg_template',
            field=models.FileField(blank=True, null=True, upload_to='config/%Y-%m', verbose_name='配置模板地址'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='cpu_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CPU核心小时单价'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='算法上市时间'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='商品简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='detail',
            field=models.CharField(default='', max_length=1000, verbose_name='商品详情'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gpu_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='GPU核心小时单价'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最近更新时间'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='pic_path',
            field=models.ImageField(default='image/default.png', upload_to='df_goods/image/%Y/%m', verbose_name='图片地址'),
        ),
    ]
