# Generated by Django 3.0.2 on 2020-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0012_auto_20200116_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='pic_path',
            field=models.ImageField(default='images/default.png', upload_to='df_goods/image/%Y/%m', verbose_name='图片地址'),
        ),
    ]
